language:
  - node_js
node_js:
  - '5'
before_install:
  - npm install gulpjs/gulp-cli#4.0 -g
install:
  - npm install
before_script:
  - gulp build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gulp unit
